// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file.sql

package db

import (
	"context"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (
  url,
  name,
  content_type,
  size,
  checksum,
  uploader
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6
) RETURNING
  id,
  url,
  name,
  content_type,
  size,
  checksum,
  uploader,
  status,
  created_at
`

type CreateFileParams struct {
	Url         string
	Name        string
	ContentType string
	Size        int64
	Checksum    string
	Uploader    string
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.Url,
		arg.Name,
		arg.ContentType,
		arg.Size,
		arg.Checksum,
		arg.Uploader,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Name,
		&i.ContentType,
		&i.Size,
		&i.Checksum,
		&i.Uploader,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getFileByURL = `-- name: GetFileByURL :one
SELECT
  id,
  url,
  name,
  content_type,
  size,
  checksum,
  uploader,
  status,
  created_at
FROM files
WHERE url = ?1
  AND status = 'NORMAL'
LIMIT 1
`

func (q *Queries) GetFileByURL(ctx context.Context, url string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByURL, url)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Name,
		&i.ContentType,
		&i.Size,
		&i.Checksum,
		&i.Uploader,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
