// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type RefreshToken struct {
	ID        int64
	Uid       string
	Token     string
	ExpiresAt int64
	CreatedAt int64
}

type User struct {
	ID           int64
	Uid          string
	Username     string
	Role         string
	Email        string
	Nickname     string
	PasswordHash string
	AvatarUrl    string
	Description  string
	Status       string
	CreatedAt    int64
	UpdatedAt    int64
}
